### ISSUE TITLE
Naksu huomaa, että Vt-X ei päällä tai Hyper-V on päällä

### ISSUE THREAD

**Issue by jonilehtola-ytl** [digabi/naksu#15]
Naksu huomaa, onko VT-X pois päältä ympäristössä tai jos Windows ympäristössä on Hyper-V-päällä
-> antaa järkevän virheilmoituksen

**Comment by mplattu** [comment]
Detecting hardware virtualisation:
 * Linux: [Check `/proc/cpuinfo`](https://www.cyberciti.biz/faq/linux-xen-vmware-kvm-intel-vt-amd-v-support/) appears to be easy by checking the CPU flags:
   * `vmx` Intel VT-x is present
   * `svm` AMD's corresponding tech is on
 * Windows: [Check `systeminfo` output](https://www.shaileshjha.com/wp-content/uploads/2017/02/systeminfo_result_hyper_v_requirements.jpg)

Detecting Hyper-V:
 * Try to detect respective service in [`Win32_Service`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-service) class

I haven't tested any of the above.

**Comment by Lateks** [comment]
Korjattu yllä viitatussa PR:ssä.
