### ISSUE TITLE
Kerää host-koneen diagnostiikkaa

### ISSUE THREAD

**Issue by jonilehtola-ytl** [digabi/naksu#16]
Naksu kerää host-koneen diagnostiikkaa
- muisti
- cpu
- fyysinen verkkointerfacen laitenimet/piirisarjat
- levy (+vapaa levy)
- host-os versio
- vagrant-versio ja VirtualBox-versio
- hostkoneen kellonajan ja päivämäärän
- käytetyt Naksun käynnistysparametrit (virtualisoitu verkkolaite)

Tallentaa sen ktp-jako-kansioon tiedostoksi.

**Comment by jonilehtola-ytl** [comment]
Lisäksi:

- mikä levy on tyypiltään (SSD/HDD)
- onko host internet-yhteydessä

**Comment by mplattu** [comment]
This has been implemented.
