### ISSUE TITLE
Naksu osaa kertoa, jos Vagrant ei yhteensopiva versio VirtualBoxin kanssa

### ISSUE THREAD

**Issue by jonilehtola-ytl** [digabi/naksu#20]
Esim. Vagrant 2.2.6 ei toimi VBox 6.1.x:n kanssa. Nyt vain `vagrant up` epäonnistuu.

**Comment by mplattu** [comment]
Outdated as Naksu is no longer using Vagrant. Naksu can suggest VirtualBox upgrade/downgrade.
