### ISSUE TITLE
Naksu ei osaa toipua, jos taustaimage/Vagrant-profiili on korruptoitunut

### ISSUE THREAD

**Issue by jonilehtola-ytl** [digabi/naksu#21]
Oire
- Naksu ei suostu käynnistymään lainkaan

Pitäisi tässä vaiheessa ehdottaa koko profiilin tyhjentämistä ja virtuaalikoneen poistoa.

**Comment by mplattu** [comment]
Any idea of the Vagrant output in this case? Any idea how to reproduce?

**Comment by mplattu** [comment]
Outdated as Naksu is no longer using Vagrant.
